---
  - name: Installing basic tools
    apt:
      pkg: "{{ item  }}"
      state: present
    with_items:
      - build-essential
      - openssl
      - libssl-dev
      - vim
      - tmux
      - rsync

  - include: nodejs.yml
  - include: yarn.yml
  - include: postgres.yml
  - include: ssh.yml

