---

- apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main
    state: present

- name: Adding apt signing keys
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present
  notify: apt-get update

- name: Installing PostgreSQL
  apt: name={{ item }} state=present allow_unauthenticated=yes
  with_items:
    - python-psycopg2
    - postgresql-10

- name: Restarting PostgreSQL
  service: name=postgresql state=restarted

- name: Creating postgres user for app
  become: yes
  become_user: postgres
  postgresql_user:
    name: "loftidev"
    password: "password"
    encrypted: yes
    role_attr_flags: CREATEDB

